teleop_twist_joy_node:
  ros__parameters:
    axis_linear.x: 1 #lefty
    scale_linear: 0.5
    axis_angular.yaw: 0 #leftx
    scale_angular: 0.5
    require_enable_button: false
    inverted_reverse: true   

joy_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0
